package com.novandi.core.consts

import com.novandi.core.domain.model.Skill

object Skills {
    fun getSkills() = listOf(
        Skill(1, "Komunikasi Efektif"),
        Skill(10, "Pengambilan Keputusan"),
        Skill(100, "Perencanaan Produksi"),
        Skill(101, "Distribusi"),
        Skill(102, "Pengangkutan"),
        Skill(103, "Pengadaan"),
        Skill(104, "Manajemen Vendor"),
        Skill(105, "Negosiasi Kontrak"),
        Skill(106, "Pengembangan Hubungan Bisnis"),
        Skill(107, "Pemrosesan Pesanan"),
        Skill(108, "Manajemen Hubungan Pelanggan"),
        Skill(109, "Analisis Tren Konsumen"),
        Skill(11, "Manajemen Proyek"),
        Skill(110, "Manajemen Pengalaman Pelanggan"),
        Skill(111, "Pengelolaan Tuntutan"),
        Skill(112, "Manajemen Layanan Purna Jual"),
        Skill(113, "Manajemen Klaim Asuransi"),
        Skill(114, "Manajemen Kualitas Layanan"),
        Skill(115, "Pengelolaan Sistem Penanganan Keluhan"),
        Skill(116, "Manajemen Pengembalian Barang"),
        Skill(117, "Manajemen Proyek Teknologi Informasi"),
        Skill(118, "Manajemen Infrastruktur TI"),
        Skill(119, "Manajemen Layanan TI"),
        Skill(12, "Analisis Data"),
        Skill(120, "Manajemen Data"),
        Skill(121, "Analitik Data"),
        Skill(122, "Visualisasi Data"),
        Skill(123, "Big Data"),
        Skill(124, "Cloud Computing"),
        Skill(125, "Manajemen Server"),
        Skill(126, "Virtualisasi"),
        Skill(127, "DevOps"),
        Skill(128, "Manajemen Aplikasi Perusahaan"),
        Skill(129, "Pengembangan Aplikasi Mobile"),
        Skill(13, "Manajemen Stres"),
        Skill(130, "Desain Aplikasi Mobile"),
        Skill(131, "Pemrograman Aplikasi Mobile"),
        Skill(132, "Manajemen Aplikasi Web"),
        Skill(133, "Manajemen API"),
        Skill(134, "Pengembangan API"),
        Skill(135, "Desain API"),
        Skill(136, "Otomasi Proses Bisnis"),
        Skill(137, "Manajemen Bisnis Digital"),
        Skill(138, "Transformasi Digital"),
        Skill(139, "E-commerce"),
        Skill(14, "Kemampuan Presentasi"),
        Skill(140, "Manajemen Pemasok E-commerce"),
        Skill(141, "Pemasaran Online"),
        Skill(142, "Pengembangan Aplikasi E-commerce"),
        Skill(143, "Manajemen Keamanan E-commerce"),
        Skill(144, "Manajemen Pembayaran Online"),
        Skill(145, "Manajemen Transaksi Online"),
        Skill(146, "Manajemen Pemasaran Digital"),
        Skill(147, "Manajemen Komunitas Online"),
        Skill(148, "Penyusunan Laporan Bisnis"),
        Skill(149, "Pengambilan Keputusan Bisnis"),
        Skill(15, "Menulis Laporan"),
        Skill(150, "Manajemen Perubahan Organisasi"),
        Skill(151, "Menyapu dan Mengepel Lantai"),
        Skill(152, "Membersihkan Jendela"),
        Skill(153, "Mencuci Piring"),
        Skill(154, "Mengemas Barang"),
        Skill(155, "Mengoperasikan Mesin Fotokopi"),
        Skill(156, "Menjaga Kebersihan Lingkungan"),
        Skill(157, "Mencuci Mobil"),
        Skill(158, "Mengangkat Barang Berat"),
        Skill(159, "Mengelola Tempat Sampah"),
        Skill(16, "Layanan Pelanggan"),
        Skill(160, "Menggunakan Peralatan Kebersihan"),
        Skill(161, "Merawat Tanaman"),
        Skill(162, "Menata Barang di Rak"),
        Skill(163, "Menyortir Barang"),
        Skill(164, "Mengemas Produk di Pabrik"),
        Skill(165, "Menyusun Dokumen"),
        Skill(166, "Mengirim Barang"),
        Skill(167, "Menghitung Barang"),
        Skill(168, "Memotong Rumput"),
        Skill(169, "Menanam Bibit Tanaman"),
        Skill(17, "Penjualan"),
        Skill(170, "Menggunakan Alat Penyiram Tanaman"),
        Skill(171, "Merawat Hewan Peliharaan"),
        Skill(172, "Menjaga Keamanan Lingkungan"),
        Skill(173, "Menggunakan Alat Pemotong"),
        Skill(174, "Menghitung Stok Barang"),
        Skill(175, "Membuat Laporan Sederhana"),
        Skill(176, "Menjaga Area Kerja Bersih"),
        Skill(177, "Menjaga Kerapihan Produk"),
        Skill(178, "Membantu Proses Produksi"),
        Skill(179, "Mengoperasikan Mesin Jahit Sederhana"),
        Skill(18, "Pengelolaan Inventaris"),
        Skill(180, "Melipat Pakaian"),
        Skill(181, "Menyusun Paket Pengiriman"),
        Skill(182, "Menjaga Gudang"),
        Skill(183, "Mengantar Barang"),
        Skill(184, "Mengecek Kondisi Barang"),
        Skill(185, "Mengoperasikan Mesin Penggiling"),
        Skill(186, "Mengoperasikan Mesin Pengemas"),
        Skill(187, "Membungkus Makanan"),
        Skill(188, "Menjaga Persediaan Barang"),
        Skill(189, "Mengontrol Kualitas Produk"),
        Skill(19, "Perencanaan Strategis"),
        Skill(190, "Mengecek Expired Date Produk"),
        Skill(191, "Mengukur Bahan dengan Akurat"),
        Skill(192, "Menyusun Barang di Gudang"),
        Skill(193, "Mengelola Inventaris Sederhana"),
        Skill(194, "Memastikan Kebersihan Alat Produksi"),
        Skill(195, "Menggunakan Alat Pemotong Kertas"),
        Skill(196, "Menjaga Keamanan Produk"),
        Skill(197, "Mengemas dan Melabeli Produk"),
        Skill(198, "Melakukan Pengawasan Sederhana"),
        Skill(199, "Mengisi Bahan Bakar"),
        Skill(2, "Kepemimpinan"),
        Skill(20, "Pengelolaan Anggaran"),
        Skill(200, "Mengoperasikan Alat Pemanas Makanan"),
        Skill(201, "Keamanan Jaringan"),
        Skill(202, "Manajemen Basis Data"),
        Skill(203, "Pengembangan Aplikasi Web"),
        Skill(204, "Manajemen Proyek TI"),
        Skill(205, "Analisis Data Besar"),
        Skill(206, "Pengembangan Aplikasi Mobile"),
        Skill(207, "Pemrograman Berorientasi Objek"),
        Skill(208, "Pemrograman Web Dinamis"),
        Skill(209, "Pengujian Perangkat Lunak"),
        Skill(21, "Kreativitas"),
        Skill(210, "Desain UX/UI"),
        Skill(211, "Manajemen Infrastruktur TI"),
        Skill(212, "Virtualisasi Infrastruktur"),
        Skill(213, "Cloud Computing"),
        Skill(214, "Pemrograman Python"),
        Skill(215, "Administrasi Sistem Linux"),
        Skill(216, "Manajemen Konten Web"),
        Skill(217, "Pengembangan API"),
        Skill(218, "Pemrograman Java"),
        Skill(219, "Pengembangan Sistem Terdistribusi"),
        Skill(22, "Kemampuan Bahasa Asing"),
        Skill(220, "Pengelolaan Infrastruktur Cloud"),
        Skill(221, "Automasi TI"),
        Skill(222, "Manajemen Basis Data NoSQL"),
        Skill(223, "Keamanan Aplikasi Web"),
        Skill(224, "Pemrograman C++"),
        Skill(225, "Pengembangan Software Agile"),
        Skill(226, "Desain Arsitektur Sistem"),
        Skill(227, "Analisis Kebutuhan TI"),
        Skill(228, "Manajemen Versi Kode"),
        Skill(229, "Pengembangan Sistem Embedded"),
        Skill(23, "Analisis Bisnis"),
        Skill(230, "Pemrograman JavaScript"),
        Skill(231, "Analisis Kinerja Sistem"),
        Skill(232, "Manajemen Proyek Agile"),
        Skill(233, "Pengujian Penetrasi"),
        Skill(234, "Pengembangan Aplikasi Desktop"),
        Skill(235, "Manajemen Jaringan"),
        Skill(236, "Pengelolaan Backup dan Pemulihan Data"),
        Skill(237, "Optimisasi Basis Data"),
        Skill(238, "Integrasi Sistem"),
        Skill(239, "Desain Database Relasional"),
        Skill(24, "Pengembangan Produk"),
        Skill(25, "Pengembangan Bisnis"),
        Skill(26, "Digital Marketing"),
        Skill(27, "SEO/SEM"),
        Skill(28, "Desain Grafis"),
        Skill(29, "Fotografi"),
        Skill(3, "Pemecahan Masalah"),
        Skill(30, "Pengelolaan Media Sosial"),
        Skill(31, "Pemasaran Konten"),
        Skill(32, "Copywriting"),
        Skill(33, "Penyuntingan Video"),
        Skill(34, "Desain UI/UX"),
        Skill(35, "Pengembangan Web"),
        Skill(36, "Pemrograman"),
        Skill(37, "Pengujian Perangkat Lunak"),
        Skill(38, "Jaringan Komputer"),
        Skill(39, "Keamanan Siber"),
        Skill(4, "Manajemen Waktu"),
        Skill(40, "Administrasi Sistem"),
        Skill(41, "Manajemen Basis Data"),
        Skill(42, "Manajemen Risiko"),
        Skill(43, "Kepatuhan Peraturan"),
        Skill(44, "Penyusunan Kontrak"),
        Skill(45, "Manajemen Rantai Pasokan"),
        Skill(46, "Analisis Pasar"),
        Skill(47, "Manajemen Sumber Daya Manusia"),
        Skill(48, "Pelatihan dan Pengembangan"),
        Skill(49, "Rekrutmen dan Seleksi"),
        Skill(5, "Keterampilan Interpersonal"),
        Skill(50, "Kompensasi dan Manfaat"),
        Skill(51, "Hubungan Karyawan"),
        Skill(52, "Pengembangan Organisasi"),
        Skill(53, "Negosiasi Gaji"),
        Skill(54, "Perencanaan Karir"),
        Skill(55, "Manajemen Perubahan"),
        Skill(56, "Manajemen Konflik"),
        Skill(57, "Penjadwalan Proyek"),
        Skill(58, "Manajemen Waktu"),
        Skill(59, "Keterampilan Persuasif"),
        Skill(6, "Kerja Tim"),
        Skill(60, "Analisis Statistik"),
        Skill(61, "Pengambilan Keputusan Berbasis Data"),
        Skill(62, "Pengelolaan Keuangan"),
        Skill(63, "Penyusunan Anggaran"),
        Skill(64, "Pengendalian Biaya"),
        Skill(65, "Perencanaan Keuangan"),
        Skill(66, "Audit Keuangan"),
        Skill(67, "Akuntansi"),
        Skill(68, "Pelaporan Keuangan"),
        Skill(69, "Perpajakan"),
        Skill(7, "Kemampuan Berpikir Kritis"),
        Skill(70, "Analisis Kredit"),
        Skill(71, "Investasi"),
        Skill(72, "Perdagangan Saham"),
        Skill(73, "Manajemen Portofolio"),
        Skill(74, "Pembiayaan Usaha"),
        Skill(75, "Perencanaan Pensiun"),
        Skill(76, "Manajemen Kekayaan"),
        Skill(77, "Asuransi"),
        Skill(78, "Real Estat"),
        Skill(79, "Manajemen Properti"),
        Skill(8, "Kemampuan Beradaptasi"),
        Skill(80, "Analisis Keuangan"),
        Skill(81, "Manajemen Risiko Keuangan"),
        Skill(82, "Pengembangan Produk Baru"),
        Skill(83, "Desain Produk"),
        Skill(84, "Manajemen Produk"),
        Skill(85, "Inovasi Produk"),
        Skill(86, "Penelitian dan Pengembangan"),
        Skill(87, "Pemodelan Keuangan"),
        Skill(88, "Pengembangan Strategi"),
        Skill(89, "Manajemen Operasi"),
        Skill(9, "Negosiasi"),
        Skill(90, "Pengendalian Mutu"),
        Skill(91, "Pengembangan Proses"),
        Skill(92, "Perbaikan Berkelanjutan"),
        Skill(93, "Lean Manufacturing"),
        Skill(94, "Six Sigma"),
        Skill(95, "Pengurangan Biaya"),
        Skill(96, "Efisiensi Operasional"),
        Skill(97, "Logistik"),
        Skill(98, "Manajemen Rantai Pasokan"),
        Skill(99, "Pengendalian Persediaan")
    )
}