package com.novandi.core.consts

import com.novandi.core.domain.model.Skill

object Skills {
    fun getSkills() = listOf(
        Skill(1, "Python"),
        Skill(2, "Adobe Photoshop"),
        Skill(3, "AutoCAD"),
        Skill(4, "Microsoft Excel"),
        Skill(5, "Bug Tracking"),
        Skill(6, "Communication"),
        Skill(7, "Machine Learning"),
        Skill(8, "Team Leadership"),
        Skill(9, "HTML"),
        Skill(10, "3D Modeling"),
        Skill(11, "Blogging"),
        Skill(12, "Adobe Premiere Pro"),
        Skill(13, "Statistical Modeling"),
        Skill(14, "Financial Analysis"),
        Skill(15, "Social Media Marketing"),
        Skill(16, "Proofreading"),
        Skill(17, "Circuit Design"),
        Skill(18, "Problem-solving"),
        Skill(19, "PHP"),
        Skill(20, "SEO"),
        Skill(21, "Social Media Management"),
        Skill(22, "Financial Planning"),
        Skill(23, "Java"),
        Skill(24, "Statistical Analysis"),
        Skill(25, "Team Coordination"),
        Skill(26, "User Interface Design"),
        Skill(27, "Product Prototyping"),
        Skill(28, "Adobe After Effects"),
        Skill(29, "Structural Analysis"),
        Skill(30, "Data Visualization"),
        Skill(31, "Front-end Development"),
        Skill(32, "Market Research"),
        Skill(33, "Data Management"),
        Skill(34, "Copy Editing"),
        Skill(35, "Brand Identity Design"),
        Skill(36, "Power Systems Engineering"),
        Skill(37, "Content Marketing"),
        Skill(38, "Interior Design"),
        Skill(39, "R"),
        Skill(40, "CAD"),
        Skill(41, "JavaScript"),
        Skill(42, "User Experience Design"),
        Skill(43, "Structural Engineering"),
        Skill(44, "Copyediting"),
        Skill(45, "Content Creation"),
        Skill(46, "CSS"),
        Skill(47, "Time Management"),
        Skill(48, "Data Entry"),
        Skill(49, "User Experience (UX) Design"),
        Skill(50, "Canva"),
        Skill(51, "Viva"),
        Skill(52, "Video editing software"),
        Skill(53, "Verbal communication skills"),
        Skill(54, "Capcut"),
        Skill(55, "Illustrator"),
        Skill(56, "Cashier Operations"),
        Skill(57, "Adobe Premiere"),
        Skill(58, "Prepare cooking ingredients"),
        Skill(59, "Mastering Balinese, Indonesian, and English language"),
        Skill(60, "Interpersonal"),
        Skill(61, "Diligent"),
        Skill(62, "Honest"),
        Skill(63, "MS Office"),
        Skill(64, "Clean cookware"),
        Skill(65, "Receive and store raw materials"),
        Skill(66, "Microsoft Office (Word, Excel, PowerPoint)"),
        Skill(67, "Precision"),
        Skill(68, "Teamwork"),
        Skill(69, "Video editing"),
        Skill(70, "Content maker"),
        Skill(71, "Culinary field"),
        Skill(72, "Good attitudes"),
        Skill(73, "Like challenging task"),
        Skill(74, "Good Presentation"),
        Skill(75, "No Specific Skill"),
        Skill(76, "SQL"),
        Skill(77, "SDLC"),
        Skill(78, "Adobe Illustrator"),
        Skill(79, "Problem Solving"),
        Skill(80, "Marketing Strategy"),
        Skill(81, "Project Planning"),
        Skill(82, "Calendar Management"),
        Skill(83, "Data Mining"),
        Skill(84, "Color Theory"),
        Skill(85, "Analytics"),
        Skill(87, "Attention to Detail"),
        Skill(88, "Web Frameworks"),
        Skill(89, "R Programming"),
        Skill(90, "Visual Design"),
        Skill(91, "Google Analytics"),
        Skill(92, "Storytelling"),
        Skill(93, "Customer Relationship Management"),
        Skill(94, "Patience"),
        Skill(95, "Responsive Design"),
        Skill(96, "Layout Design"),
        Skill(97, "Documentation"),
        Skill(98, "Keyboarding Skills"),
        Skill(99, "Research"),
        Skill(100, "Prospecting"),
        Skill(101, "Administrative Support"),
        Skill(102, "Software Development Life Cycle"),
        Skill(103, "Typography"),
        Skill(104, "Task Management"),
        Skill(105, "Organization"),
        Skill(106, "Usability Testing"),
        Skill(107, "Campaign Optimization"),
        Skill(108, "Data Accuracy"),
        Skill(109, "Order Management"),
        Skill(110, "Accuracy"),
        Skill(111, "Editing"),
        Skill(112, "Negotiation"),
        Skill(113, "SEM"),
        Skill(114, "Copywriting"),
        Skill(115, "Product Knowledge"),
        Skill(116, "Content Strategy"),
        Skill(117, "Organizational Skills"),
        Skill(118, "Team Management"),
        Skill(119, "Version Control"),
        Skill(120, "Social Media Advertising"),
        Skill(121, "Database Design"),
        Skill(122, "Creativity"),
        Skill(123, "Adaptability"),
        Skill(124, "Leadership"),
        Skill(125, "Agile Methodology"),
        Skill(126, "Search Engine Optimization"),
        Skill(127, "C++"),
        Skill(128, "Risk Management"),
        Skill(129, "Client Relationship Management"),
        Skill(130, "Excel"),
        Skill(131, "Data Analysis"),
        Skill(132, "Creative Writing"),
        Skill(133, "Leadership Skills"),
        Skill(134, "Event Planning"),
        Skill(135, "Financial Reporting"),
        Skill(136, "Statistics"),
        Skill(137, "SEO Optimization"),
        Skill(138, "Database Management"),
        Skill(139, "Wireframing"),
        Skill(140, "Employee Relations"),
        Skill(141, "Agile Development"),
        Skill(142, "Illustration"),
        Skill(143, "Content Editing"),
        Skill(144, "Media Relations"),
        Skill(145, "Data Cleaning"),
        Skill(146, "Negotiation Skills"),
        Skill(147, "Prototyping"),
        Skill(148, "Database Administration"),
        Skill(149, "Logo Design"),
        Skill(150, "Organization Skills"),
        Skill(151, "Data Modeling"),
        Skill(152, "Conflict Resolution"),
        Skill(153, "Brand Management"),
        Skill(154, "Requirement Gathering"),
        Skill(155, "HTML/CSS"),
        Skill(156, "Data Cleansing"),
        Skill(157, "Java Programming"),
        Skill(158, "Python Programming"),
        Skill(159, "JavaScript Programming"),
        Skill(160, "Ruby on Rails"),
        Skill(161, "Microsoft Office"),
        Skill(162, "UI/UX design")
    )

    fun getSkillById(id: Int) = getSkills().filter { skill -> skill.id == id }[0]
}